[Cookies]
PSID = "Fill out with your __Secure-1PSID cookie value from Chrome DevTools > Application > Cookies > .google.com"
PSIDTS = "Fill out with your __Secure-1PSIDTS cookie value from Chrome DevTools > Application > Cookies > .google.com"

[Server]
host = 0.0.0.0
port = 6969

[Proxy]
url =
